#include <stdio.h>
#include <stdlib.h>
#include <time.h>
int main()
{
    int number, guess, no_guesses=1;
    srand(time(0));
    number = rand() % 100 + 1;
    // printf("the number is %d\n", number);
    printf("A random no is generated by the system.\n\n");
    do
    {
        printf("Guess the number between 1 and 100\n\n");
        scanf("%d", &guess);
        if (guess>number)
        {
            printf("Enter a smaller number\n\n");
        }
        else if (guess<number)
        {
            printf("Enter a bigger number\n\n");
            
        }
        else{
            printf("congratulations you guessed the correct number in %d attempts\n\n", no_guesses);
        }
        no_guesses++;
    } while (guess!=number);
    
    return 0;
}